import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import Dashboard from '../components/Home/Dashboard'
import { useUserContext } from '../contexts/UserContext'
import * as UserService from '../hooks/useSessionStorage'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const userContext = useUserContext();
  const router = useRouter();
  
  useEffect(() => {
    const userName = sessionStorage.getItem('userName');
    const profileColor = sessionStorage.getItem('profileColor');
    if (!userName && !profileColor) {
      router.push('/User')
    }
    else if(userName && profileColor){
      userContext.setUserName(userName);
      userContext.setProfileColor(profileColor);
    }
  }, []);

  return (
    <div className={styles.home_container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </div>
  )
}

export default Home
